#!/bin/bash
# Compile all simulation programs with the SIML compiler.
# Usefull before putting the models to the website.

set -x #enable debug output

compiler="python simlc --debug-areas=perf"
#compiler="pypy simlc --debug-areas=perf"
#compiler="/home/eike/codedir/pypy-dist/pypy-c simlc --debug-areas=perf"

find -L . -name "*.siml" -exec $compiler {} ";"
