#!/bin/bash
# Compile all simulation programs with the SIML compiler.
# Usefull before putting the models to the website.

set -x #enable debug output

compiler="python simlc --debug-area=perf"
#compiler="pypy simlc"
find -L . -name "*.siml" -exec $compiler {} ";"
