#!/usr/bin/python

#Read a Python program and create a long string from it, that can be inseted into c++ programs.
#Each line is prepended by a '\"' character and sthe string "\n\"" is appended to each line.
#All appearences of the character '\"' inside a line are eacaped.


inFile  = open('simulatorbase.py', 'r')
outFile = open('simulatorbase.h', 'w')

outFile.write('//This file was generated by the script "py2c_string".\n\n')

for inLine in inFile:
    outLine = '"' + inLine.replace('"', '\\"').replace('\n', '') + '\\n"\n'
    print outLine, #debug output
    outFile.write(outLine)

inFile.close()
outFile.close()

