#!/usr/bin/env python
################################################################################
#                            Warning: Do not edit!                             #
#                                                                              #
# This file is generated, it will be overwritten every time the source file(s) #
# is/are changed.                                                              #
# If you want to change the behaviour of a simulation object                   #
# write a main routine in an other file. Use import or execfile to load        #
# the objects defined in this file into the Python interpreter.                #
################################################################################
# Generated by SIML compiler version 0.3.0 on 2007-02-12 00:24:08. 
# Source file(s): /home/eike/codedir/freeode/trunk/models/biological/bioreactor_simple.siml
################################################################################


from numpy import array, sqrt
#from scipy import *
from freeode.simulatorbase import SimulatorBase
from freeode.simulatorbase import simulatorMainFunc


class Batch(SimulatorBase): 
    ''' 
    Object to simulate process Batch 
    Definition in
    file: '/home/eike/codedir/freeode/trunk/models/biological/bioreactor_simple.siml'
    line: 3 
    ''' 
    
    def __init__(self): 
        super(Batch, self).__init__() 
        self.defaultFileName = 'Batch.simres' 
        #create all parameters with value 0; to prevent runtime errors. 
        self.p_mu_max = 0.0 
        self.p_solutionParameters_simulationTime = 0.0 
        self.p_Ks = 0.0 
        self.p_solutionParameters_reportingInterval = 0.0 
        self.p_Yxs = 0.0 


    def initialize(self,  *args, **kwArgs): 
        ''' 
        Compute parameter values and 
        compute initial values of state variables 
        ''' 
        #create all variables with value 0; to prevent runtime errors.
        v_mu = 0.0 
        v_S = 0.0 
        v_X = 0.0 
        #create dict for parameter override 
        ovd = self._createParamOverrideDict(args, kwArgs) 
        #do computations 
        self.p_solutionParameters_simulationTime = 20.0
        self.p_solutionParameters_reportingInterval = 0.1
        self.p_mu_max = 0.32
        self.p_Ks = 0.01
        self.p_Yxs = 0.5
        v_X = 0.1
        v_S = 20.0
        
        #assemble initial values to array and store them 
        self.initialValues = array([v_S, v_X, ], 'float64')
        self.stateVectorLen = len(self.initialValues) 
        #put algebraic variables into array, only to compute its size 
        algVars = array([v_mu, ], 'float64')
        self.algVectorLen = len(algVars) 
        #Create maping between variable names and array indices 
        self.variableNameMap = {'S':0, 'X':1, 'mu':2, }


    def dynamic(self, time, state, returnAlgVars=False): 
        ''' 
        Compute time derivative of state variables. 
        This function will be called by the solver repeatedly. 
        ''' 
        #take the state variables out of the state vector 
        v_S = state[0] 
        v_X = state[1] 
        #do computations 
        v_mu = self.p_mu_max*v_S/(v_S + self.p_Ks)
        v_X_dt = v_mu*v_X
        v_S_dt =  -1.0/self.p_Yxs*v_mu*v_X
        
        if returnAlgVars: 
            #put algebraic variables into array 
            algVars = array([v_mu, ], 'float64')
            return algVars 
        else: 
            #assemble the time derivatives into the return vector 
            stateDt = array([v_S_dt, v_X_dt, ], 'float64')
            return stateDt 


    def final(self): 
        ''' 
        Display and save simulation results. 
        This function will be called once; after the simulation results 
        have been computed. 
        ''' 
        #the final method's statements 
        self.graph(['mu', 'X', 'S', ], ) 
        print 'simulation Batch finished.'
        




#Main function - executed when file (module) runs as an independent program.
#When file is imported into other programs, if-condition is false.
if __name__ == '__main__':
    simulatorClasses = [Batch, ]
    simulatorMainFunc(simulatorClasses) #in module simulatorbase

