#!/usr/bin/env python
################################################################################
#                            Warning: Do not edit!                             #
#                                                                              #
# This file is generated, it will be overwritten every time the source file(s) #
# is/are changed.                                                              #
# If you want to change the behavior of a simulation object                    #
# write a main routine in an other file. Use import or execfile to load        #
# the objects defined in this file into the Python interpreter.                #
################################################################################
# Generated by SIML compiler version 0.4.0a2 on 2009-06-21 02:14:15. 
# Source file: fibonacci_compile_time.siml
################################################################################


from numpy import array
from math import pi, sin, cos, tan, sqrt, exp, log
from freeode.simulatorbase import SimulatorBase
from freeode.simulatorbase import simulatorMainFunc




#Main function - executed when file (module) runs as an independent program.
#When file is imported into other programs, if-condition is false.
if __name__ == '__main__':
    simulatorClasses = []
    simulatorMainFunc(simulatorClasses) #in module simulatorbase

